CC=gcc
CFLAGS=-lpthread -Wall

all: main

exo1:
	$(CC)  -Wall exo1.c -o exo1.o $(CFLAGS)
	./exo1.o

exo2:
	$(CC)  -Wall exo2.c -o exo2.o $(CFLAGS)
	./exo2.o

exemple6:
	$(CC)  -Wall exemple_6.c -o exemple6.o $(CFLAGS)
	./exemple6.o

