CC=gcc
CFLAGS=-Wall -lpthread -lm

all: main

main:
	${CC} -o main.o main.c ${CFLAGS}

test: main
	./main.o 1
	./main.o 2
	./main.o 3
	./main.o 4
	./main.o 5
	./main.o 6
	./main.o 7
	./main.o 8
	./main.o 9
	./main.o 10